### ISSUE TITLE
a little suggestion for line format judgement of meth_file (Methylation info file) for get_methylation_levels.py

### ISSUE THREAD

**Issue by Reemann** [wwang-chcn/wwang_bioinfo_tools#1]
https://github.com/wwang-chcn/wwang_bioinfo_tools/blob/79a3af2b38b7b77acd7971993944fa2e9d57576f/get_methylation_levels.py#L92
There will be an extra line at the bottom of .bam.G.bed generated by mcall using BAM files as input. If using SAM files instead, this line won't be added into .sam.G.bed. This line may be caused by a bug in mcall, but not solved till now.
The extra line is "Binary file (standard input) matches". It looks like this:
![image](https://user-images.githubusercontent.com/74175760/101872169-c2ec7200-3bbf-11eb-9698-defeef54e30d.png)
Would you mind change line 92 in get_methylation_levels.py to something like this to avoid error caused by the extra line?
`if line[0] == '#' or '\t' not in line or not line:`

**Comment by wwang-chcn** [comment]
Thanks for your advice.
