### ISSUE TITLE
A confusion about "basic_QC" function in RNAseq_PE.sh at line 99 and line 103

### ISSUE THREAD

**Issue by Reemann** [wwang-chcn/wwang_bioinfo_tools#2]
Hallo, when using code "RNAseq_PE.sh", the read distribution file can only generate for refSeq genes. However, I have both "${genomeVersion}.ensGene.bed" and" ${genomeVersion}.refGene.bed" under "~/source/bySpecies/${genomeVersion}" direction. 

Should line 99 and line 103 exclude the character "!"?

<img width="1224" alt="image" src="https://user-images.githubusercontent.com/74175760/115956482-86e2f980-a52f-11eb-931e-3579570fc65e.png">

**Comment by wwang-chcn** [comment]
Yes, you are right. I have fixed it in 95912fb .
