### ISSUE TITLE
Is removing duplicates necessary before peak-calling?

### ISSUE THREAD

**Issue by Reemann** [wwang-chcn/wwang_bioinfo_tools#4]
The fragments of TF ChIP-seq data are duplicate-removed before peak-calling. 
https://github.com/wwang-chcn/wwang_bioinfo_tools/blob/a167dd80bd7fc9ab04eecd7a552c000efa1976b5/pipeline/ChIP_TF/ChIP_PE_TF_ctr.sh#L113
However, fragments of histone ChIP-seq data contain duplicates.
https://github.com/wwang-chcn/wwang_bioinfo_tools/blob/a167dd80bd7fc9ab04eecd7a552c000efa1976b5/pipeline/histone/ChIP_PE_nucleosome_narrow.sh#L88

May I ask a question on this issue that is removing duplicates necessary before peak-calling?

Thanks

**Comment by wwang-chcn** [comment]
First, the MACS will remove duplicates fragments/reads by default.
Second, there is difference between pipeline for these two types of sequencing data.
Third, https://github.com/wwang-chcn/wwang_bioinfo_tools/commit/41caf3f7f7cfee0233c6af908687aa94411f15f0 solved the inconsistence about fragments/reads duplicate between pipelines.
