### ISSUE TITLE
Can you show more example ?

### ISSUE THREAD

**Issue by hmyh1202** [wwang-chcn/wwang_bioinfo_tools#5]
hello:

    Nice job，so can you show more information about Input methylation info of  DNAme folder？ 

Than you 
The best !

**Comment by wwang-chcn** [comment]
The input meth file for this scripts is the output file from mCall (tools in [MOABS](https://github.com/sunnyisgalaxy/moabs)) which have 15 columns.
|column name|type|example|
|-|-|-|
|chrom|string|chr1|
|start|int|1740|
|end|int|1742|
|ratio|float|0.7|
|totalC|int|20|
|methC|int|14|
|strand|string|B|
|next|string|G|
|Plus|string|+|
|totalC|int|17|
|methC|int|13|
|Minus|string|-|
|totalC|int|3|
|methC|int|1|
|localSeq|string|ATCGA|

**Comment by hmyh1202** [comment]
So if I only use CpG sites ( only use + strand ),  can the software suit for that data format ?

**Comment by wwang-chcn** [comment]
Actually, the scripts get the DNAme info from the first 6 columns.

PS: I recommended using [DNAme data processing pipeline](https://github.com/wwang-chcn/wwang_bioinfo_tools/tree/master/pipeline/DNAme) to get these DNAme info file.
https://github.com/wwang-chcn/wwang_bioinfo_tools/blob/41caf3f7f7cfee0233c6af908687aa94411f15f0/pipeline/DNAme/DNAme_PE.sh#L52
The output file *.G.bed is the input of these scripts.
